name: CI/CD Pipeline

env:
  registryNameFQDN: ahcsawth31containerregistry.azurecr.io
  registryName: ahcsawth31containerregistry
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: ./Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}
  
on:
  push:
    branches: [ main ]
    paths: Application/*

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs:
  dockerBuildPush:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.registryNameFQDN }}
        # Username used to log against the Docker registry
        username: ${{ secrets.ACR_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.ACR_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true
        
    - name: Docker Build
      run: docker build -t $registryNameFQDN/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
      
    - name: Docker Push
      run: docker push $registryNameFQDN/$repositoryName:$tag
      
  Deploy-DevEnv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: dockerBuildPush
    environment: Dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
    
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@main
        with:
            subscriptionID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: WTH31
            template: "ARM-Templates/container-webapp-template.json"
            parameters: webAppName=AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }} registryName=${{ env.registryName }}
      - name: Wait / Sleep
        # You may pin to the exact commit or the version.
        # uses: jakejarvis/wait-action@919fc193e07906705e5b7a50f90ea9e74d20b2b0
        uses: jakejarvis/wait-action@v0.1.1
        with:
          # Follows the Linux sleep syntax for time units: a number followed by s for seconds, m for minutes, etc
          time: 30s
    
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
            app-name: AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }}
            images: ${{ env.registryNameFQDN }}/wth/dotnetcoreapp:${{ env.tag }}
            
  Deploy-TestEnv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Deploy-DevEnv
    environment: Test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
    
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@main
        with:
            subscriptionID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: WTH31
            template: "ARM-Templates/container-webapp-template.json"
            parameters: webAppName=AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }}  registryName=${{ env.registryName }}
     
      - name: Wait / Sleep
        # You may pin to the exact commit or the version.
        # uses: jakejarvis/wait-action@919fc193e07906705e5b7a50f90ea9e74d20b2b0
        uses: jakejarvis/wait-action@v0.1.1
        with:
          # Follows the Linux sleep syntax for time units: a number followed by s for seconds, m for minutes, etc
          time: 30s
      
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
            app-name: AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }}
            images: ${{ env.registryNameFQDN }}/wth/dotnetcoreapp:${{ env.tag }}
            
  Deploy-ProdEnv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Deploy-TestEnv
    environment: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
    
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@main
        with:
            subscriptionID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: WTH31
            template: "ARM-Templates/container-webapp-template.json"
            parameters: webAppName=AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }}  registryName=${{ env.registryName }}
      
      - name: Wait / Sleep
        # You may pin to the exact commit or the version.
        # uses: jakejarvis/wait-action@919fc193e07906705e5b7a50f90ea9e74d20b2b0
        uses: jakejarvis/wait-action@v0.1.1
        with:
          # Follows the Linux sleep syntax for time units: a number followed by s for seconds, m for minutes, etc
          time: 30s
      
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
            app-name: AHCSAdevops-wth31-${{ secrets.ENVIRONMENT }}
            images: ${{ env.registryNameFQDN }}/wth/dotnetcoreapp:${{ env.tag }}


